airbnb/hypernova

README.md
Just a small change that corrects the React code example specified in the README.
=> Fix React syntax typo in README

README.md
While ES modules are nice, they're currently not supported on latest
Node and they transpile a bit complicated on latest babel. In order to
simplify the example so one can get running as fast as possible we can
just switch over to using plain CommonJS modules which are simple enough
to understand.
Fixes #19 
@ljharb
=> Switches to CJS in examples

src/utils/BatchManager.js, src/utils/renderBatch.js, test/renderBatch-test.js
If a promise is rejected with no error now the serialization to error
won't fail because the stack is empty.
Fixes #15 and adds a few tests + regression tests.
@ljharb
=> Allows non instanceOf Error to be thrown

src/coordinator.js
```
> let os = require('os')
undefined
> os.cpus()
[ { model: 'Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz',
speed: 2494,
times: 
{ user: 379945100,
nice: 8095800,
sys: 53693800,
idle: 67719016300,
irq: 9700 } } ]
> 
> os.cpus().length -1 
0
```
😅
We shouldn't assume all CPUs are declared as multicore especially when running on virtual server environments.
=> Default WORKER_COUNT to 1 when cpu count is 1

docs/client-spec.md
@ljharb 
This is to ensure that the HTML key is not null and that this stuff happens before afterResponse and onSuccess is called.
=> [docs] Ensure HTML key is a string

src/createVM.js
@ljharb 
This adds flexibility to the environment option. By passing in name we can bootstrap different environments for different bundles.
=> Adds name to environment

docs/client-spec.md
Spec currently states that we should call String/toString on the
response after we've called afterResponse method. This change is to
relax those requirements enabling you to pass whatever type you'd like.
The end result should still be a string (of HTML ideally) but I don't
think we have to specify that.
@ljharb
=> Relaxes the spec requirements for afterResponse

src/utils/BatchManager.js
This commit passes the `context` object as a 2nd arg to
getComponent. The point of this is so that getComponent can have access
to the props objects as well as any other future items we decide
to pass into context.
@ljharb
=> Adds more flexibility for retrieving components

src/utils/BatchManager.js
On some cases we pass/throw a non-error, we used to wrap that in an
Error and then serialize that new error. The problem with that approach
is that the stack trace would be completely lost.
Now we either include the original stack trace or no stack trace at all.
Because an incorrect stack trace is worse than no stack trace.
@ljharb @lencioni
=> Fixes exception handling stack traces

CHANGELOG.md, README.md, src/index.js, test/client-test.js, test/escape-test.js
Piggybacks off of #10 
Main change here is that we're changing `fromScript` and `toScript` to only accept an object which maps its keys => data attribute, and value => data attribute's value. The data attributes will be encoded to make sure they're lower-case and only contain alphanumeric + `-`. The value is encoded as well as it encodes quotes so that selecting won't break with arbitrary inputs.
@ljharb
=> Lets one render the same component many times

README.md
Addresses https://github.com/airbnb/hypernova/issues/58
=> Remove old config option text from README

README.md, src/coordinator.js, src/server.js, test/coordinator-test.js
This branch adds a `cpu` config option, to cap the number of workers Hypernova spawns
(This is desirable in deployments where we'd like to control the number of cpus per container)
Thanks!
=> Make number of CPUs configurable

README.md, src/server.js, src/worker.js
We'd like to be able to configure the host that express binds to.
This new config option passes it along, and defaults to `0.0.0.0`.
=> Add option to configure host

examples/simple/config/routes.rb
I'd like to suggest a minor adjustment to examples/simple where the root route is set to welcome index.
I believe that the intent of this example is to be able to see hypernova in action for someone new to it (like me).
Through the process of making it work, one would likely encounter issues on their local development machine (such as npm and/or node versions). Once setup issues get resolved, one might still believe that something is wrong when getting the Rails page when accessing root. Consequently, such a change would make it more straightforward that everything is good to go hence driving adoption.
On a side note, I deployed the simple example to Heroku because I wanted to confirm that hypernova could be relevant for my projects deployment. This worked (see …
=> change welcome index to root in routes for examples/simple

src/utils/lifecycle.js, src/utils/renderBatch.js, src/worker.js
`return null` in Promise then callback to suppress Bluebird warning.
Though this is not required by ES6 Promise specification, this repo should comply to Bluebird best practice unless using it. Otherwise redundant log is printed out into console in development, which is annoying and have nothing to do with hypernova or its users:
From Bluebird: http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it
> If you know what you're doing and don't want to silence all warnings, you can create runaway promises without causing this warning by returning e.g. null:
```js
getUser().then(function(user) {
// Perform this in the "background" and don't care about its result at all
saveAnalytics(user);
// return a non-undefined value to …
```
=> [Fix] Add return in Promise 'then' callback

README.md
The legacy named `devMode` has done nothing but ensure that we run on a single process since way back. This correctly describes what devMode does.
Fixes #87
=> Changes docs to accurately reflect devMode

src/utils/BatchManager.js, test/BatchManager-test.js
As a safeguard -- in case a developer pops out of the promise chain an
error happens and Hypernova is unable to catch it -- we can detect whether
something is "off" by inspecting `html`. The html returned should be a
string and exist. If it does not exist then that's a sign that something
is wrong and needs investigation. This should prevent errors from
slipping through the cracks.
=> If invalid HTML is returned we reject with an err

docs/clients.md
We've just open sourced our client to hypernova! This is for [Pyramid](https://trypyramid.com/https://trypyramid.com/), a python web framework.
https://github.com/Yelp/pyramid-hypernova
Thanks!
=> Add client pyramid-hypernova

README.md, src/server.js, src/utils/lifecycle.js, src/utils/renderBatch.js, test/lifecycle-test.js, test/renderBatch-test.js
Previously, we dispatched all jobs in a batch concurrently.  Rendering
jobs are compute bound, so we would not actually get parallel execution.
One effect of this is that timers for a job in plugins record a start
time from the point where all jobs are dispatched and record the end
time after all or most of the jobs have completely finished.  This
prevents us from being able to reliably tell how much latency a single
job contributes to the total latency (for instance, if job A takes
500ms, and job B and C each take 25ms, we may get results that would
indicate that jobs A, B, and C each spent 550ms executing, which is true
in a way, but unhelpful).
This change executes the jobs serially as a chain.
This should have no or minimal impact either way on actual response
time.
This is intended …
=> Execute jobs in a batch in serial

src/utils/lifecycle.js
Also, turns out you can call `clearTimeout` on anything.  Even the `if (timeout)` is unnecessary.
/cc @goatslacker
=> Clear timeout in raceTo

README.md, src/server.js, src/worker.js
The previous version is highly tied to a cluster-based
coordinator/worker model with some custom lifecycle management.  To
allow experimentation with other process/configuration management, it is
helpful to break up and export some of the components of the server
configuration.  This preserves the old interface, but allows an a la
carte option.
Currently the configuration allows the host and port for the hypernova
server to be specified.  This change allows alternate listening
arrangements to be made, such as Unix domain sockets.  I like Unix
domain sockets.
/cc @goatslacker @ljharb
=> Export server components and allow listening on unix domain sockets

src/server.js, src/utils/logger.js
Currently, config can specify the options to be passed to the
constructed winston logger, but the specific transport is hard coded as
Console.  Some applications may wish to use other transports like Syslog
that are defined in other packages.
This change adds a config field, `loggerInstance`, that allows an
arbitrarily constructed logger to be passed in.  Really any object that
implements `log` should work, but this is intended for other winston
loggers.
/cc @goatslacker
=> Allow a logger instance to be injected via the configuration

README.md, src/server.js, test/server-test.js
In our project, we need to add more middlewares than just the logger to express. Hypernova starts the server automatically and returns an express instance already initialized and we cannot add middlewares afterwords. 
If we can pass the instance of express and prevent hypernova to create a new one, then we have more control over additional features to express (and maybe this is useful for other people as well). By default, if we don't pass any express instance, then hypernova will create and handle it.
=> Add option to pass an express instance in the configuration

src/worker.js
The graceful shutdown mechanism is only available for clustered installations (e.g. devMode = true). In our production stack, we are currently using multiple (HAProxy managed) single threaded instances of hypernova (e.g. devMode = true). This instances are actually systemd units so our init script is something along the lines of
```bash
start_nova_workers() {
for worker in $(nova_workers); do
echo "Start ${worker}"
systemctl start ${worker}
done
fi
}
```
Shutdown and restart is similar.
When we want to updated these instances, we do a rolling restart with HAProxy, which kills signals to each worker, in a round-robin manner, and re spawns it. There is a race condition in this shutdown process with open connections (as there is in the clustered version of hypernova). This patch introduces …
=> worker: Add graceful shutdown

src/worker.js
Hello. Once the PR adding graceful shutdown (#147), we noticed that
the default exit code is non-zero and can affect some external systems.
Since the shutdown is graceful, it makes sense to exit the process with
0 instead of the default value (currently 1). This will help process
management software (e.g. systemd) identify that the process exited
normally.
In a side note, we could re-iterate the default exit code of
`shutDownSequence` as 0 would make more sense. I can update my
patch to reflect this changes.
=> worker: Change graceful shutdown exit code

README.md, src/index.js, test/index-test.js
*Context:*
Currently, I'm working on a framework using Hypernova and I've been writing some custom [bindings](https://github.com/ara-framework/ara-cli/wiki/Supported-Hypernova-Bindings) for other libraries like Vue.js, Svelte, etc. 
I'm getting the `data-*` values, but I think I need a way to warranty that the data attributes will be the same that `hypernova` is using if they change in the future.
https://github.com/ara-framework/hypernova-redom/blob/feat/render-client/src/index.js#L18
=> Make DATA_KEY and DATA_ID attributes  importable
